title: Starblog
description: Yet another blog
url: https://mathiasd.fr
baseurl: ""

commit_sha: "<%= ENV['JEKYLL_COMMIT_SHA'] %>"

collections:
  articles:
    output: true
    permalink: /p/:slug/

markdown: kramdown
highlighter: rouge

kramdown:
  input: SubSup
  syntax_highlighter: rouge

exclude:
- noise

sass:
  sass_dir: _sass
  style: compressed

feed:
  icon: /assets/favicon.png
  path: ""
  excerpt_only: true
  collections:
    articles:
      path: /feed.xml

plugins:
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-hackclub
