title: Starblog
description: Yet another blog
url: https://mathiasd.fr
baseurl: ""

HACKCLUB_API: "https://hackclub.mathiasd.fr"
commit_sha: "<%= ENV['JEKYLL_COMMIT_SHA'] %>"

collections:
  articles:
    output: true
    permalink: /p/:slug/

defaults:
  - scope:
      path: ""
      type: articles
    values:
      date: 1999-01-01 00:00:00 +0000

markdown: kramdown
highlighter: rouge

kramdown:
  input: SubSup
  syntax_highlighter: rouge

exclude:
- noise

sass:
  sass_dir: _sass
  style: compressed

feed:
  icon: /assets/favicon.png
  path: ""
  excerpt_only: true
  collections:
    articles:
      path: /feed.xml

plugins:
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-hackclub
  